// Generated by React Router

import "react-router";

declare module "react-router" {
	interface Register {
		pages: Pages;
		routeFiles: RouteFiles;
		routeModules: RouteModules;
	}
}

type Pages = {
	"/": {
		params: {};
	};
	"/character/:characterId": {
		params: {
			characterId: string;
		};
	};
};

type RouteFiles = {
	"root.tsx": {
		id: "root";
		page: "/" | "/character/:characterId";
	};
	"routes/layout.tsx": {
		id: "routes/layout";
		page: "/" | "/character/:characterId";
	};
	"routes/home.tsx": {
		id: "routes/home";
		page: "/";
	};
	"routes/character.tsx": {
		id: "routes/character";
		page: "/character/:characterId";
	};
};

type RouteModules = {
	root: typeof import("./app/root.tsx");
	"routes/layout": typeof import("./app/routes/layout.tsx");
	"routes/home": typeof import("./app/routes/home.tsx");
	"routes/character": typeof import("./app/routes/character.tsx");
};
